# Generated by Django 3.2.12 on 2022-04-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Відповідь')),
                ('author', models.CharField(max_length=30, verbose_name='Автор')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Питання')),
                ('author', models.CharField(max_length=30, verbose_name='Автор')),
                ('isClosed', models.BooleanField(verbose_name='Cтатус')),
                ('date', models.DateField()),
            ],
        ),
    ]
