# Generated by Django 3.2.12 on 2022-05-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advice_app', '0004_alter_answer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-id']},
        ),
    ]
