# Generated by Django 3.2.12 on 2022-05-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice_app', '0005_alter_answer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='isClosed',
            field=models.BooleanField(default=0, verbose_name='Cтатус'),
        ),
    ]
