# Generated by Django 3.2.12 on 2022-05-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice_app', '0006_alter_post_isclosed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key_words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.TextField(max_length=50)),
                ('posts', models.ManyToManyField(to='advice_app.Post')),
            ],
        ),
    ]
