# Generated by Django 3.2.12 on 2022-05-18 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advice_app', '0007_key_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='key_words',
            old_name='line',
            new_name='word',
        ),
    ]
