# Generated by Django 3.2.12 on 2022-05-18 21:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('advice_app', '0008_rename_line_key_words_word'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Key_words',
            new_name='KeyWords',
        ),
        migrations.RenameModel(
            old_name='My_user',
            new_name='MyUser',
        ),
    ]
